### ISSUE TITLE
The stylesheet leaks into all pages

### ISSUE THREAD

**Issue by Chaosmeister** [aljawaid/PluginManager#27]
After installing the PluginManager, all pages get styled with the plugin-manager.css

**Comment by aljawaid** [comment]
Please send screenshots... which styles?  If you have KanboardCSS installed, it is normal.  Some of the text styles could possibly crossover to other pages but I would need to know which/where the text is in order to target it.

**Comment by aljawaid** [comment]
> After installing the PluginManager, all pages get styled with the plugin-manager.css

the whole of the plugins/extensions section gets restyled.

**Comment by aljawaid** [comment]
Looking at the stylesheet a bit closer, you may be possibly affected by:
- text links colour
- text links hover
- page margins
- sidebar

None of the above should cause a negative impact to your instance. Either way, I would need more specific information.

**Comment by Chaosmeister** [comment]
heyo,
I don't use KanboardCSS

examples:

in ?controller=DashboardController
![image](https://user-images.githubusercontent.com/13346344/205006895-8634eae6-dfb8-47ef-82da-c721f75adb3e.png)

- boardnames get underlined

in ?controller=BoardViewController
![image](https://user-images.githubusercontent.com/13346344/205007063-ef3b9aea-4dd0-494b-82e7-1742f8f6300a.png)

- the columns suddenly have a border
- links are underlined

**Comment by aljawaid** [comment]
Cool, I will work on those shortly

**Comment by aljawaid** [comment]
Done, I will release a new version once the plugin actually gets listed. #26

**Comment by Chaosmeister** [comment]
the table  still gets borders  from here

![image](https://user-images.githubusercontent.com/13346344/205027124-f7402006-2375-43c0-be2a-a65bb5f17a4b.png)

on the board view, tasks also still get underlined by this
![image](https://user-images.githubusercontent.com/13346344/205027356-e2825a3f-c049-4e3d-860c-6a74552cc9fe.png)

maybe it would be easier to just include the pluginmanager css on the pluginmanager site?

**Comment by aljawaid** [comment]
> maybe it would be easier to just include the pluginmanager css on the pluginmanager site?
what do you mean?

**Comment by Chaosmeister** [comment]
you could for example only hook the css or the whole plugin if `controller=PluginController`

**Comment by aljawaid** [comment]
> you could for example only hook the css or the whole plugin if `controller=PluginController`

I'm not sure I understand what you mean... any sample code to share?

**Comment by Chaosmeister** [comment]
something like this:

```php
public function initialize()
{
    // abort initialization on non pluginmanager sites
    if ("PluginController" != $this->request->getStringParam("controller"))
    {
        return;
    }
```
